#ifndef _MODBUS_CONFIG_H
#define _MODBUS_CONFIG_H


#define MBS_TX_EN_PIN_IN_INTERRUPT		1
#define MBS_UART_RX_USING_INTERRUPT		0
#define MBS_UART_RX_USING_TIMER         0
#define MBS_UART_TX_USING_INTERRUPT		0


#endif //_MODBUS_CONFIG_H
